### PR TITLE
Add files via upload for landmark uncertainty dataset

### PR DESCRIPTION
**Pull request by Schobs**
Adds data for landmark uncertainty.

### Description
Adds tabular data for the landmark uncertainty example file. The dataset is called the Cardiac Landmark Uncertainty Estimation Dataset.

### Status
**Complete**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

### CODE REVIEW

**Review by haipinglu — COMMENTED** [review]
- One Q about file names, e.g. `checkpointuncertainty_pairs_B5_EEB_pairs_test_l2`. Such long names may need some explanation to understand, and may not be necessary, e.g. does removing `checkpoint` lose anything? What EEB and B5 (I guess it is Bin 5) stand for?
- Validation set naming conventions `val`, e.g. `checkpointuncertainty_pairs_B5_EEB_pairs_test_l2`. We have a discussion on this at https://github.com/pykale/pykale/issues/275 and our decision was to use `valid`. Neither is perfect but we should follow a convention when agreed.
- It may be **a plus** to add this link to the TMI paper to submit indicating that we shared not only the code, but also (some) data to ensure reproducibility and further exploration by other researchers.

**Comment by Schobs** [comment]
I have addressed the issues! Good idea about mentioning in TMI, I have made a note.

**Review by haipinglu — COMMENTED** [review]
Great to see you zip them for easy io (note we have API in pykale to download and unzip zip files).

One last Q: in `uncertainty_pairs_pairs_test`, what's the difference between the first `pairs` and the second `pairs`?

**Comment by Schobs** [comment]
> Great to see you zip them for easy io (note we have API in pykale to download and unzip zip files).
> 
> One last Q: in `uncertainty_pairs_pairs_test`, what's the difference between the first `pairs` and the second `pairs`?

Error in the ReadMe file. Have fixed it.

**Pull request merged**
